lib/bios/common.robot: improve matching pattern
It is very interesting that incorrect pattern fails because of
underlying logic:

KEYWORD ${matches} = BuiltIn . Run Keyword And Return Status Should Match, ${item}, *${option}*
Documentation:

23:12:21.311 	TRACE 	Arguments: [ '2. AHCI/0: QEMU HARDDISK ATA-7 Hard-Disk (20480 MiBytes)' | '*[setup]*' ]
23:12:21.311 	TRACE 	Return: None
23:12:21.311 	TRACE 	Return: True
23:12:21.311 	INFO 	${matches} = True

So this one return True, but following one return False:

KEYWORD ${matches} = BuiltIn . Run Keyword And Return Status Should Match, ${item}, *${option}*
Documentation:

Fails if the given string does not match the given pattern.
Start / End / Elapsed: 	20241216 23:12:21.307 / 20241216 23:12:21.309 / 00:00:00.002
23:12:21.307 	TRACE 	Arguments: [ '1. DVD/CD [AHCI/2: QEMU DVD-ROM ATAPI-4 DVD/CD]' | '*[setup]*' ]
23:12:21.308 	FAIL 	'1. DVD/CD [AHCI/2: QEMU DVD-ROM ATAPI-4 DVD/CD]' does not match '*[setup]*'
23:12:21.309 	DEBUG 	Traceback (most recent call last):
  None
AssertionError: '1. DVD/CD [AHCI/2: QEMU DVD-ROM ATAPI-4 DVD/CD]' does not match '*[setup]*'
23:12:21.309 	TRACE 	Return: False
23:12:21.309 	INFO 	${matches} = False

Signed-off-by: Piotr Król <piotr.krol@3mdeb.com>