regression-scope/osfv_regression_scope.py: allow setting reference rev via flag
It worked for other commands, but not for the "commands" command. The
error was:

  File "/home/macpijan/projects/github/dasharo/open-source-firmware-validation/./scripts/ci/regression-scope/osfv_regression_scope.py", line 87, in <module>
    fire.Fire(CLI)
    ~~~~~~~~~^^^^^
  File "/home/macpijan/projects/github/dasharo/open-source-firmware-validation/venv/lib/python3.13/site-packages/fire/core.py", line 135, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
  File "/home/macpijan/projects/github/dasharo/open-source-firmware-validation/venv/lib/python3.13/site-packages/fire/core.py", line 468, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
                                ~~~~~~~~~~~~~~~~~~~^
        component,
        ^^^^^^^^^^
    ...<2 lines>...
        treatment='class' if is_class else 'routine',
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        target=component.__name__)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/macpijan/projects/github/dasharo/open-source-firmware-validation/venv/lib/python3.13/site-packages/fire/core.py", line 684, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
  File "/home/macpijan/projects/github/dasharo/open-source-firmware-validation/./scripts/ci/regression-scope/osfv_regression_scope.py", line 65, in commands
    print(" ".join(parser.commands()))
          ~~~~~~~~^^^^^^^^^^^^^^^^^^^
TypeError: sequence item 0: expected str instance, list found

Signed-off-by: Maciej Pijanowski <maciej.pijanowski@3mdeb.com>